package com.example.inventorymanager.core

class Constants {
    companion object {
        //Room
        const val PROVIDER_TABLE = "provider"
        const val CUSTOMER_TABLE = "customer"
        const val INVENTORY_TABLE = "inventory"
        const val PRODUCT_TABLE = "product"
        const val ORDER_TABLE = "order"
        const val TRANSFER_TABLE = "transfer"
        const val WAREHOUSE_TABLE = "warehouse"
        const val LOCATION_TABLE = "location"
        const val DELIVERY_TABLE = "delivery"
        const val DELIVERY_DETAILS_TABLE = "delivery_details"
        const val ORDER_DETAILS_TABLE = "order_details"

        //Screens
        const val ADD_DELIVERY_SCREEN = "Add Delivery"
        const val ADD_LOCATION_SCREEN = "Add Location"
        const val ADD_ORDER_SCREEN = "Add Order"
        const val ADD_PRODUCT_SCREEN = "Add Product"
        const val ADD_PROVIDER_SCREEN = "Add Provider"
        const val ADD_TRANSFER_SCREEN = "Add Transfer"
        const val ADD_WAREHOUSE_SCREEN = "Add Warehouse"
        const val ADD_CUSTOMER_SCREEN = "Add Customer"
        const val UPDATE_DELIVERY_SCREEN = "Update Delivery"
        const val UPDATE_LOCATION_SCREEN = "Update Location"
        const val UPDATE_ORDER_SCREEN = "Update Order"
        const val UPDATE_PRODUCT_SCREEN = "Update Product"
        const val UPDATE_PROVIDER_SCREEN = "Update Provider"
        const val UPDATE_TRANSFER_SCREEN = "Update Transfer"
        const val UPDATE_WAREHOUSE_SCREEN = "Update Warehouse"
        const val UPDATE_CUSTOMER_SCREEN = "Update Customer"
        const val DELIVERY_LIST_SCREEN = "Delivery List"
        const val LOCATION_LIST_SCREEN = "Location List"
        const val ORDER_LIST_SCREEN = "Order List"
        const val PRODUCT_LIST_SCREEN = "Product List"
        const val PROVIDER_LIST_SCREEN = "Provider List"
        const val TRANSFER_LIST_SCREEN = "Transfer List"
        const val WAREHOUSE_LIST_SCREEN = "Warehouse List"
        const val CUSTOMER_LIST_SCREEN = "Customer List"
        const val SEARCH_SCREEN = "Search"
        const val ABOUT_SCREEN = "About"
        const val SETTINGS_SCREEN = "Settings"
        const val HELP_SCREEN = "Help"
        const val LOGOUT_SCREEN = "Logout"
        const val LOGIN_SCREEN = "Login"
        const val REGISTER_SCREEN = "Register"
        const val HOME_SCREEN = "Home"


        //Arguments
        const val BOOK_ID = "bookId"

        //Actions
        const val ADD_CUSTOMER = "Add A Customer."
        const val ADD_DELIVERY = "Add A Delivery."
        const val UPDATE_CUSTOMER = "Update a customer."
        const val UPDATE_DELIVERY = "Update a delivery."
        const val DELETE_DELIVERY = "Delete a delivery."
        const val DELETE_PROVIDER = "Delete a provider."
        const val UPDATE_PROVIDER = "Update a provider."
        const val ADD_PROVIDER = "Add a provider."
        const val ADD_PRODUCT = "Add a product."
        const val UPDATE_PRODUCT = "Update a product."
        const val DELETE_PRODUCT = "Delete a product."
        const val ADD_WAREHOUSE = "Add a warehouse."
        const val UPDATE_WAREHOUSE = "Update a warehouse."
        const val DELETE_WAREHOUSE = "Delete a warehouse."
        const val ADD_TRANSFER = "Add a transfer."
        const val UPDATE_TRANSFER = "Update a transfer."
        const val DELETE_TRANSFER = "Delete a transfer."
        const val ADD_LOCATION = "Add a location."
        const val UPDATE_LOCATION = "Update a location."
        const val DELETE_LOCATION = "Delete a location."
        const val ADD_ORDER = "Add an order."
        const val UPDATE_ORDER = "Update an order."
        const val DELETE_ORDER = "Delete an order."
        const val ADD_DELIVERY_DETAILS = "Add delivery details."
        const val UPDATE_DELIVERY_DETAILS = "Update delivery details."
        const val DELETE_DELIVERY_DETAILS = "Delete delivery details."
        const val ADD_ORDER_DETAILS = "Add order details."
        const val UPDATE_ORDER_DETAILS = "Update order details."
        const val DELETE_ORDER_DETAILS = "Delete order details."
        const val ADD_INVENTORY = "Add inventory."
        const val UPDATE_INVENTORY = "Update inventory."
        const val DELETE_INVENTORY = "Delete inventory."
        const val ADD_CUSTOMER_DETAILS = "Add customer details."
        const val UPDATE_CUSTOMER_DETAILS = "Update customer details."
        const val DELETE_CUSTOMER_DETAILS = "Delete customer details."
        const val ADD_CUSTOMER_ORDER = "Add customer order."
        const val UPDATE_CUSTOMER_ORDER = "Update customer order."
        const val DELETE_CUSTOMER_ORDER = "Delete customer order."
        const val ADD_CUSTOMER_TRANSFER = "Add customer transfer."
        const val ADD_CUSTOMER_DELIVERY = "Add customer delivery."
        const val UPDATE_CUSTOMER_DELIVERY = "Update customer delivery."
        const val DELETE_CUSTOMER_DELIVERY = "Delete customer delivery."
        const val ADD_CUSTOMER_PRODUCT = "Add customer product."
        const val UPDATE_CUSTOMER_PRODUCT = "Update customer product."
        const val DELETE_CUSTOMER_PRODUCT = "Delete customer product."
        const val ADD_CUSTOMER_WAREHOUSE = "Add customer warehouse."
        const val DELETE_CUSTOMER = "Delete a customer."

        //Buttons
        const val ADD_BUTTON = "Add"
        const val DISMISS_BUTTON = "Dismiss"
        const val UPDATE_BUTTON = "Update"

        //Placeholders
        const val AUTHOR = "Type the author name..."
        const val CUSTOMER_NAME = "Customer Name"
        const val CUSTOMER_ADDRESS = "Customer Address"
        const val EMPTY_STRING = ""
    }
}